import mongoose from "mongoose";
const { Schema } = mongoose;

//Since only TODOName is required, so only TODOName is there in scheme, id automatically generated by MongoDB
const TODOSchema = new Schema({
  todoName: String,
});

//Model object generated
const Todos = mongoose.model("Todos", TODOSchema);

export default Todos;
